### ISSUE TITLE
Embedding dimension 1536 does not match collection dimensionality 1024

### ISSUE THREAD

**Issue by sf6532** [AlaGrine/RAG_chatabot_with_Langchain#1]
as soon as I start chatting with one of my doc I have this error...

any ideas why ?

**Comment by AlaGrine** [comment]
1536 is the embedding dimension of the "text-embedding-ada-002" model from OpenAI.
1024 is the embedding dimension of "thenlper/gte-large" from Hugging Face.

The current version of the application uses the following embedding models:
- text-embedding-ada-002 (dimension 1536) if LLM provider = OpenAI;
- thenlper/gte-large (dimension 1024) when LLM provider = Hugging Face;
- models/embedding-001 (dimension 768) if LLM provider = Google.


"Embedding dimension 1536 does not match collection dimension 1024" means that you have tried to open a chroma vector dB created using the gte-large embedding model while the selected LLM provider is OpenAI.
